### PR TITLE
Use quad-double arithmetic

### LINKED ISSUE #97: Error while computing the the intersection of two SphericalPolygons
Hello,

I am trying to compute the intersection of two polygons (triangles in this examples).

Following the code, I have implemented this example which fails:
```
import math
import numpy
from spherical_geometry.polygon import SphericalPolygon

def convertGPSCoordinatesToSphericalCoordinates(GPSCoordinates, radius):

    x = radius * math.cos(math.radians(GPSCoordinates[0])) * math.cos(math.radians(GPSCoordinates[1]))
    y = radius * math.cos(math.radians(GPSCoordinates[0])) * math.sin(math.radians(GPSCoordinates[1]))
    z = radius * math.sin(math.radians(GPSCoordinates[0]))

    return [x, y, z]

def convert(points):
    convertedPoints = []

    for point in points:
        convertedPoints.append(convertGPSCoordinatesToSphericalCoordinates(point, 1))

    convertedPoints.append(convertGPSCoordinatesToSphericalCoordinates(points[0], 1))

    return SphericalPolygon(convertedPoints)

p1 = [
    [
        40.91351257612757,
        29.06982421875
    ],
    [
        40.34654412118006,
        -3.66943359375
    ],
    [
        52.48278022207823,
        13.38134765625
    ],
]

p2 = [
    [
        48.83579746243093,
        2.35107421875
    ],
    [
        41.9022770409637,
        12.54638671875
    ],
    [
        48.10743118848039,
        11.66748046875
    ],
]

sp1 = convert(p1)
sp2 = convert(p2)
i = sp1.intersection(sp2)
```

When computing the intersection, the program crash and I got the following error:
```
Traceback (most recent call last):
  File "/Users/felixveysseyre/Projects/.../test.py", line 64, in <module>
    i = sp1.intersection(sp2)
  File "/Users/felixveysseyre/Projects/.../lib/python2.7/site-packages/spherical_geometry/polygon.py", line 950, in intersection
    return g.intersection()
  File "/Users/felixveysseyre/Projects/.../lib/python2.7/site-packages/spherical_geometry/graph.py", line 503, in intersection
    self._remove_exterior_edges()
  File "/Users/felixveysseyre/Projects/.../lib/python2.7/site-packages/spherical_geometry/graph.py", line 720, in _remove_exterior_edges
    great_circle_arc.midpoint(A._point, B._point))):
  File "/Users/felixveysseyre/.../lib/python2.7/site-packages/spherical_geometry/polygon.py", line 305, in contains_point
    return self._contains_point(point, self._points, self._inside)
  File "/Users/felixveysseyre/Projects/.../lib/python2.7/site-packages/spherical_geometry/polygon.py", line 286, in _contains_point
    intersects = great_circle_arc.intersects(P[:-1], P[1:], r, point)
  File "/Users/felixveysseyre/Projects/.../lib/python2.7/site-packages/spherical_geometry/great_circle_arc.py", line 250, in intersects
    return math_util.intersects(A, B, C, D)
ValueError: intersects: Input operand 2 does not have enough dimensions (has 0, gufunc core with signature (i),(i),(i),(i)->() requires 1)
```

Am I doing something wrong ?

Thanks for your time and your work.

### PR DESCRIPTION
**Pull request by mdboom**
In investigating #97, I experimented with using quad-double arithmetic, rather than the double-double currently being used.  **IT DOESN'T ACTUALLY RESOLVE #97**, however, I thought it might be helpful to share the changes required to use quad-double arithmetic anyway, just in case it's useful in the future.

### CODE REVIEW

**Comment by mdboom** [comment]
Thanks for the 🎉 , folks.  Believe it or not, I'm looking at this code again toward an application for retinal image montaging.  Same sort of issues apply.  Of course, those are not-quite-spheres, which makes this even more complicated.

**Comment by pllim** [comment]
Glad to hear from you again! If you ever find a use for Astropy for retinal imaging... :pray: :pray: :pray:

**Comment by pllim** [comment]
Test failures are for shady Python versions, which I think should not be included in Travis anyway.

**Comment by pllim** [comment]
@bernie-simon , can we merge this?

**Comment by bernie-simon** [comment]
Some day we ought to come up with a better algorithm that doesn't need quad precision, but until then, this will do.

**Pull request merged**
