### PR TITLE
Set min astropy version to 5.0.4

### PR DESCRIPTION
**Pull request by WilliamJamieson**

### CODE REVIEW

**Comment by WilliamJamieson** [comment]
Note we we need to update all the CI to eliminate python 3.7 as astropy 5+ is only supported on python 3.8+

**Review by mcara — APPROVED** [review]
Into the future!

**Comment by mcara** [comment]
I guess this cannot be tested with Python 3.7.

**Comment by pllim** [comment]
@WilliamJamieson , pls open a follow up PR to set minimum Python to be 3.8 like you did with stsci.tools . Thanks!

spacetelescope/stsci.tools#146

**Comment by WilliamJamieson** [comment]
> @WilliamJamieson , pls open a follow up PR to set minimum Python to be 3.8 like you did with stsci.tools . Thanks!
> 
> [spacetelescope/stsci.tools#146](https://github.com/spacetelescope/stsci.tools/pull/146)

See #219.

**Pull request merged**
