### PR TITLE
BLD: Use numpy 2.x ABI

### PR DESCRIPTION
**Pull request by pllim**
BLD: Use numpy 2.x ABI.

DEP: Clean up dependencies and associated docs.

Fix https://github.com/spacetelescope/spherical_geometry/issues/272

### CODE REVIEW

**Comment by pllim** [comment]
With this patch, C-ext is now available in devdeps, see https://github.com/spacetelescope/spherical_geometry/actions/runs/9099962846/job/25013742232?pr=274

`test_basic.py::test_math_util_inner1d PASSED`

**Comment by mcara** [comment]
Why use a not-yet-released version (of numpy) when building releases?

**Comment by pllim** [comment]
You can wait to merge, no rush on my side. I was just trying to see if this would fix the problem of C-extension not on `devdeps` and it does.

**Comment by mcara** [comment]
> I was just trying to see if this would fix the problem of C-extension not on `devdeps` and it does.

I know it does. I mentioned this in https://github.com/spacetelescope/spherical_geometry/pull/265#issuecomment-2106356771 and https://github.com/spacetelescope/spherical_geometry/pull/265#discussion_r1598976025

**Comment by pllim** [comment]
Ah, sorry if I missed it! I think this diff just need minor tweaks when numpy 2.0 is released.

**Comment by mcara** [comment]
The code was tested to work with C extension build agains numpy 2.0.0.dev0 and so if numpy will not make any dramatic changes before an official release - the code will work just fine once numpy 2.0.0 is officially released. If I have to choose between building with an officially release version and not tests devdeps vs building with an experimental version but being able to test with latest alpha/beta numpy, I would prefer the former.

**Comment by pllim** [comment]
> if numpy will not make any dramatic changes before an official release

Last I heard, they were debating whether to drop Python 3.9 or not. 😬 

Anyways, like I said, you can keep this open for now if you want to wait. I am not asking for you to merge this today.

**Comment by zacharyburnett** [comment]
sorry, I didn't see this PR before merging #279; this PR will need to be rebased

**Review by mcara — APPROVED** [review]

**Pull request merged**
