### PR TITLE
Remove std::max function from quad precision library

### PR DESCRIPTION
**Pull request by bernie-simon**
The std::max function is not supported in Microsoft C++. This fix removes the function and replaces it with code that does the same thing so that this library can be used on Windows systems.

### CODE REVIEW

**Comment by pllim** [comment]
Your commits look sketchy, except for the last one.

**Comment by pllim** [comment]
xref  conda-forge/staged-recipes#3388

**Comment by bernie-simon** [comment]
Git and github seem to have a mind of their own as far as making commits go. I have my own system for branching and merging, would be happy to adopt another one that works better.

**Comment by mcara** [comment]
> The std::max function is not supported in Microsoft C++.

Very strange, see https://msdn.microsoft.com/en-us/library/a3xbc7ya.aspx

**Comment by bernie-simon** [comment]
Forty years as a programmer has taught me that you don't win an argument with the compiler.

**Comment by pllim** [comment]
You can effectively just do a `git rebase -i HEAD~9` and drop all those unnecessary commits.

**Comment by mcara** [comment]
> Forty years as a programmer has taught me that you don't win an argument with the compiler.

Try including ``<algorithm>`` when in Visual Studio and you may win this time 😄

**Pull request merged**
