### PR TITLE
Update the setup files and documentation for the package

### PR DESCRIPTION
**Pull request by bernie-simon**
The travis file was updated to better match the astropy template. I updated the requirements in the README file file and removed the cut line section and replaced it on a section on disjoint polygons to reflect how the code now works. I fixed the github project name in the setup config file and bumped the version number in the stup file.

### CODE REVIEW

**Comment by pllim** [comment]
Ops, my bad. I committed a clean up of `.travis.yml` to `master` directly earlier today. You'll have to resolved the conflict on your end.

**Comment by pllim** [comment]
Something is wrong with your `.travis.yml`, tests are failing.

**Comment by bernie-simon** [comment]
Yes, I know :-(

**Comment by pllim** [comment]
Maybe because you changed the language to C? Also, use the "squash and merge" option since one of your commits here is "merge from master".

**Comment by pllim** [comment]
Tests passed. :smile:

**Pull request merged**
