### PR TITLE
TST: OSX ARM64 throws RuntimeWarning now

### PR DESCRIPTION
**Pull request by pllim**
I don't know why though.

xref #262

### CODE REVIEW

**Comment by pllim** [comment]
Huh, CI was disabled due to inactivity. I have to close/reopen to trigger it. The OSX ARM64 wheel job did pass though, but this is more like a bandaid. I think we need to understand why it is throwing RuntimeWarning and not ValueError as stated here:

https://github.com/spacetelescope/spherical_geometry/blob/5de7fc79d8e3cb4f1c0a9338acf06b350d17b15b/src/math_util.c#L250-L255

Thanks to @jhunkeler for digging out the code.

**Comment by pllim** [comment]
devdeps failure is unrelated (#261)

**Review by mcara — CHANGES_REQUESTED** [review]
hiding these errors is not a good solution.

**Comment by mcara** [comment]
The problems appear to be due to import failure of `math_util` even though `math_util...so` is built. very strange. If this import fails, the code fallback to the Python code. Probably that code is buggy too and hence the errors. So, two things need to be fixed: Python code and import of the compiled C module build with numpy 2.0.

**Comment by pllim** [comment]
OK then I'll leave it to the experts. Thanks!

**Pull request closed without merging**
